const dishPopularityData = [
  { name: 'Chicken Biryani', popularityScore: 10, category: 'Rice' },
  { name: 'Mutton Biryani', popularityScore: 10, category: 'Rice' },
  { name: 'Veg Biryani', popularityScore: 8, category: 'Rice' },
  { name: 'Paneer Biryani', popularityScore: 9, category: 'Rice' },
  { name: 'Egg Biryani', popularityScore: 9, category: 'Rice' },
  { name: 'Jeera Rice', popularityScore: 6, category: 'Rice' },
  { name: 'Steamed Rice', popularityScore: 5, category: 'Rice' },
  { name: 'Lemon Rice', popularityScore: 7, category: 'Rice' },
  { name: 'Curd Rice', popularityScore: 6, category: 'Rice' },
  { name: 'Pulao', popularityScore: 7, category: 'Rice' },

  { name: 'Chicken Curry', popularityScore: 9, category: 'Main Course' },
  { name: 'Butter Chicken', popularityScore: 10, category: 'Main Course' },
  { name: 'Kadai Chicken', popularityScore: 9, category: 'Main Course' },
  { name: 'Chicken Masala', popularityScore: 9, category: 'Main Course' },
  { name: 'Chicken Do Pyaza', popularityScore: 8, category: 'Main Course' },
  { name: 'Egg Curry', popularityScore: 8, category: 'Main Course' },
  { name: 'Fish Curry', popularityScore: 8, category: 'Main Course' },
  { name: 'Mutton Curry', popularityScore: 9, category: 'Main Course' },
  { name: 'Keema Masala', popularityScore: 8, category: 'Main Course' },
  { name: 'Chicken Korma', popularityScore: 9, category: 'Main Course' },

  { name: 'Paneer Butter Masala', popularityScore: 9, category: 'Paneer' },
  { name: 'Kadai Paneer', popularityScore: 9, category: 'Paneer' },
  { name: 'Palak Paneer', popularityScore: 8, category: 'Paneer' },
  { name: 'Shahi Paneer', popularityScore: 9, category: 'Paneer' },
  { name: 'Paneer Tikka Masala', popularityScore: 9, category: 'Paneer' },
  { name: 'Matar Paneer', popularityScore: 8, category: 'Paneer' },
  { name: 'Paneer Bhurji', popularityScore: 8, category: 'Paneer' },
  { name: 'Paneer Lababdar', popularityScore: 9, category: 'Paneer' },
  { name: 'Paneer Korma', popularityScore: 8, category: 'Paneer' },
  { name: 'Achari Paneer', popularityScore: 8, category: 'Paneer' },

  { name: 'Dal Tadka', popularityScore: 6, category: 'Dal' },
  { name: 'Dal Fry', popularityScore: 6, category: 'Dal' },
  { name: 'Yellow Dal', popularityScore: 5, category: 'Dal' },
  { name: 'Mixed Dal', popularityScore: 6, category: 'Dal' },
  { name: 'Dal Makhani', popularityScore: 8, category: 'Dal' },
  { name: 'Rajma', popularityScore: 8, category: 'Dal' },
  { name: 'Chole', popularityScore: 8, category: 'Dal' },
  { name: 'Kadhi Pakora', popularityScore: 7, category: 'Dal' },
  { name: 'Sambar', popularityScore: 7, category: 'Dal' },
  { name: 'Rasam', popularityScore: 6, category: 'Dal' },

  { name: 'Roti', popularityScore: 6, category: 'Bread' },
  { name: 'Chapati', popularityScore: 6, category: 'Bread' },
  { name: 'Phulka', popularityScore: 6, category: 'Bread' },
  { name: 'Paratha', popularityScore: 8, category: 'Bread' },
  { name: 'Aloo Paratha', popularityScore: 9, category: 'Bread' },
  { name: 'Paneer Paratha', popularityScore: 9, category: 'Bread' },
  { name: 'Naan', popularityScore: 8, category: 'Bread' },
  { name: 'Butter Naan', popularityScore: 9, category: 'Bread' },
  { name: 'Kulcha', popularityScore: 8, category: 'Bread' },
  { name: 'Bhatura', popularityScore: 9, category: 'Bread' },

  { name: 'Aloo Gobi', popularityScore: 7, category: 'Vegetable' },
  { name: 'Aloo Matar', popularityScore: 7, category: 'Vegetable' },
  { name: 'Mix Veg', popularityScore: 6, category: 'Vegetable' },
  { name: 'Bhindi Masala', popularityScore: 7, category: 'Vegetable' },
  { name: 'Baingan Bharta', popularityScore: 7, category: 'Vegetable' },
  { name: 'Methi Sabzi', popularityScore: 6, category: 'Vegetable' },
  { name: 'Cabbage Sabzi', popularityScore: 5, category: 'Vegetable' },
  { name: 'Beans Poriyal', popularityScore: 5, category: 'Vegetable' },
  { name: 'Gobi Manchurian', popularityScore: 8, category: 'Vegetable' },
  { name: 'Veg Kofta', popularityScore: 8, category: 'Vegetable' },

  { name: 'Idli', popularityScore: 8, category: 'Breakfast' },
  { name: 'Dosa', popularityScore: 9, category: 'Breakfast' },
  { name: 'Masala Dosa', popularityScore: 10, category: 'Breakfast' },
  { name: 'Uttapam', popularityScore: 8, category: 'Breakfast' },
  { name: 'Upma', popularityScore: 6, category: 'Breakfast' },
  { name: 'Poha', popularityScore: 7, category: 'Breakfast' },
  { name: 'Pongal', popularityScore: 7, category: 'Breakfast' },
  { name: 'Puri Bhaji', popularityScore: 9, category: 'Breakfast' },
  { name: 'Medu Vada', popularityScore: 8, category: 'Breakfast' },
  { name: 'Bread Butter', popularityScore: 5, category: 'Breakfast' },

  { name: 'Omelette', popularityScore: 8, category: 'Breakfast' },
  { name: 'Boiled Eggs', popularityScore: 6, category: 'Breakfast' },
  { name: 'Cornflakes', popularityScore: 5, category: 'Breakfast' },
  { name: 'Milk', popularityScore: 5, category: 'Breakfast' },
  { name: 'Tea', popularityScore: 7, category: 'Beverage' },
  { name: 'Coffee', popularityScore: 7, category: 'Beverage' },
  { name: 'Lassi', popularityScore: 8, category: 'Beverage' },
  { name: 'Buttermilk', popularityScore: 6, category: 'Beverage' },
  { name: 'Lemon Juice', popularityScore: 7, category: 'Beverage' },
  { name: 'Fruit Juice', popularityScore: 8, category: 'Beverage' },

  { name: 'Curd', popularityScore: 6, category: 'Sides' },
  { name: 'Raita', popularityScore: 7, category: 'Sides' },
  { name: 'Onion Salad', popularityScore: 6, category: 'Sides' },
  { name: 'Green Salad', popularityScore: 6, category: 'Sides' },
  { name: 'Papad', popularityScore: 6, category: 'Sides' },
  { name: 'Pickle', popularityScore: 6, category: 'Sides' },
  { name: 'Coconut Chutney', popularityScore: 8, category: 'Sides' },
  { name: 'Mint Chutney', popularityScore: 7, category: 'Sides' },
  { name: 'Tomato Chutney', popularityScore: 7, category: 'Sides' },
  { name: 'Peanut Chutney', popularityScore: 7, category: 'Sides' },

  { name: 'Gulab Jamun', popularityScore: 9, category: 'Dessert' },
  { name: 'Rasgulla', popularityScore: 8, category: 'Dessert' },
  { name: 'Kheer', popularityScore: 8, category: 'Dessert' },
  { name: 'Halwa', popularityScore: 8, category: 'Dessert' },
  { name: 'Fruit Custard', popularityScore: 8, category: 'Dessert' },
  { name: 'Ice Cream', popularityScore: 9, category: 'Dessert' },
  { name: 'Jalebi', popularityScore: 9, category: 'Dessert' },
  { name: 'Payasam', popularityScore: 8, category: 'Dessert' },
  { name: 'Kesari', popularityScore: 7, category: 'Dessert' },
  { name: 'Ladoo', popularityScore: 8, category: 'Dessert' },

  { name: 'Veg Fried Rice', popularityScore: 7, category: 'Rice' },
  { name: 'Hakka Noodles', popularityScore: 8, category: 'Main Course' },
  { name: 'Schezwan Noodles', popularityScore: 8, category: 'Main Course' },
  { name: 'Manchurian', popularityScore: 8, category: 'Main Course' },
  { name: 'Chilli Paneer', popularityScore: 9, category: 'Main Course' },
  { name: 'Chilli Chicken', popularityScore: 9, category: 'Main Course' },
  { name: 'Veg Cutlet', popularityScore: 7, category: 'Snacks' },
  { name: 'Samosa', popularityScore: 8, category: 'Snacks' },
  { name: 'Pakora', popularityScore: 7, category: 'Snacks' },
  { name: 'Khichdi', popularityScore: 6, category: 'Main Course' },
];

export default dishPopularityData;
